//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatHealthTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Daylist
    {
        public Daylist()
        {
            this.Exerciselogs = new HashSet<Exerciselog>();
            this.Foodlogs = new HashSet<Foodlog>();
        }
    
        public int DayID { get; set; }
        public string Dayname { get; set; }
    
        public virtual ICollection<Exerciselog> Exerciselogs { get; set; }
        public virtual ICollection<Foodlog> Foodlogs { get; set; }
    }
}
