//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatHealthTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exerciselog
    {
        public int ExerciseID { get; set; }
        public string ExerciseType { get; set; }
        public int Duration { get; set; }
        public int CaloriesBurn { get; set; }
        public int UserID { get; set; }
        public int DayID { get; set; }
    
        public virtual Daylist Daylist { get; set; }
        public virtual User User { get; set; }
    }
}
