//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatHealthTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Foodlog
    {
        public int LogID { get; set; }
        public string FoodName { get; set; }
        public int DayID { get; set; }
        public int Calories { get; set; }
        public int UserID { get; set; }
        public int FoodID { get; set; }
    
        public virtual Daylist Daylist { get; set; }
        public virtual Foodlist Foodlist { get; set; }
        public virtual User User { get; set; }
    }
}
