//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatHealthTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Foodlist
    {
        public Foodlist()
        {
            this.Foodlogs = new HashSet<Foodlog>();
        }
    
        public int FoodID { get; set; }
        public string FoodType { get; set; }
        public string FoodBrand { get; set; }
        public string Notes { get; set; }
    
        public virtual ICollection<Foodlog> Foodlogs { get; set; }
    }
}
