//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatHealthTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Exerciselogs = new HashSet<Exerciselog>();
            this.Foodlogs = new HashSet<Foodlog>();
            this.Goallogs = new HashSet<Goallog>();
        }
    
        public int UserID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public int BreedID { get; set; }
    
        public virtual Breed Breed { get; set; }
        public virtual ICollection<Exerciselog> Exerciselogs { get; set; }
        public virtual ICollection<Foodlog> Foodlogs { get; set; }
        public virtual ICollection<Goallog> Goallogs { get; set; }
    }
}
